// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0O7bOlrX4KmgQnIxzC3I4CAUD214Wss',
    appId: '1:537958801865:android:d8d3840fa450f9066e4818',
    messagingSenderId: '537958801865',
    projectId: 'chat-app-ffb92',
    storageBucket: 'chat-app-ffb92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7F_w_qvJeCunF9Iqu4hsppqgOd6JdhQ',
    appId: '1:537958801865:ios:9af6831ebcc35aab6e4818',
    messagingSenderId: '537958801865',
    projectId: 'chat-app-ffb92',
    storageBucket: 'chat-app-ffb92.appspot.com',
    androidClientId: '537958801865-qv320b8l6d1aq12mkquq78f5h1phlr26.apps.googleusercontent.com',
    iosClientId: '537958801865-qk8otdgk0tp4vuqh1cqiui8lb5opfh8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
